import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import NextAuthSessionProviders from "@/Providers/NextAuthSessionProviders";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
         <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <NextAuthSessionProviders>
        <div className="flex flex-col min-h-screen">
<Navbar></Navbar>
       <main className="flex-grow max-w-[1200px] mx-auto w-full">
         {children}
         <Toaster position="top-right" />

       </main>
       <footer>
        <Footer></Footer>
       </footer>
        </div>
         </NextAuthSessionProviders>
      </body>
     
       
     
    </html>
  );
}
